[[redirects]]
  from = "/flux"
  to = "https://j4cks-flux.vercel.app/"
  status = 200
  force = true

[[redirects]]
  from = "/flux/*"
  to = "https://j4cks-flux.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://jacks.media/docs/tutorial-extras/qi"
  to = "https://jacks.media/docs/tutorial-extras/chi"
  status = 301
  force = false